---   
 - name: "[{{ vm_name }}]: Check inception directory"
   stat:
     path: ~/inception
   register: inception_dir

 - name: "[{{ vm_name }}]: copy inception from my server to the remote one"
   copy:
     src: ../inception
     dest: ~/
   when: not inception_dir.stat.exists

 - name: "[{{ vm_name }}]: Update APT repositories"
   become: yes
   apt:
     update_cache: yes

 - name: "[{{ vm_name }}]: Install Ansible"
   become: yes
   apt:
     name: ansible
     state: present

 - name: "[{{ vm_name }}]: Run the playbook"
   command: ansible-playbook ~/inception/setup_inception_VM.yml -e "wordpress_host={{ public_ip }}"

 - name: "[{{ vm_name }}]: Print success message"
   debug:
     msg: "Inception has been successfully run on {{ vm_name }} and available on https://{{ public_ip }}"
