---   
 - name: "[{{ vm_name }}]: Check if Git repository exists"
   stat:
     path: ~/42_cloud1
   register: destination_stat
   check_mode: no

 - name: "[{{ vm_name }}]: Clone Git repository if it doesn't exist"
   git:
     repo: https://github.com/Obito-git/42_cloud1.git
     dest: ~/42_cloud1
   when: not destination_stat.stat.exists 

 - name: "[{{ vm_name }}]: Update APT repositories"
   become: yes
   apt:
     update_cache: yes

 - name: "[{{ vm_name }}]: Install Ansible"
   become: yes
   apt:
     name: ansible
     state: present

 - name: "[{{ vm_name }}]: Run the playbook"
   command: ansible-playbook 42_cloud1/inception/setup_inception_VM.yml -e "wordpress_host={{ public_ip }}"

 - name: "[{{ vm_name }}]: Print success message"
   debug:
     msg: "Inception has been successfully run on {{ vm_name }} and available on {{ public_ip }}"
