---
- name: Connect to the VM via SSH and run 'ls'
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run Azure CLI command to get Public IP
      shell: az vm show -d -g default_inception_group -n testvm001 --query publicIps -o tsv
      register: public_ip_result

    - name: SSH into the VM and run 'ls'
      ansible.builtin.shell: |
        sshpass -p "PJ3fTwX0wxEE4yd" ssh -o StrictHostKeyChecking=no hello@"{{ public_ip_result.stdout }}" '
          git clone https://github.com/Obito-git/42_cloud1.git &&
          sudo apt update &&
          sudo apt install -y ansible &&
          ansible-book 42_cloud1/
        '
