version: "3.9"
services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception_net
    volumes:
      - www:/var/www/html
    ports:
      - "443:443"
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    env_file: .env
    networks:
      - inception_net
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception_net
    volumes:
      - www:/var/www/html
    restart: always

volumes:
  www:
    driver: local
    driver_opts:
      type: none
      device: /home/amyroshn/data/www
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/amyroshn/data/database
      o: bind

networks:
  inception_net:
    name: inception_net
    driver: bridge
