---
- name: Connect to the VM via SSH and run 'ls'
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run Azure CLI command to get Public IP
      shell: az vm show -d -g default_inception_group -n testvm001 --query publicIps -o tsv
      register: public_ip_result

    - name: SSH into the VM and run 'ls'
      ansible.builtin.shell: |
        sshpass -p "PJ3fTwX0wxEE4yd" ssh -o StrictHostKeyChecking=no hello@"{{ public_ip_result.stdout }}" '
          rm -rf 42_cloud1 &&
          git clone https://github.com/Obito-git/42_cloud1.git &&
          cp 42_cloud1/srcs/install_dependencies.sh ./ &&
          sh install_dependencies.sh &&
          cp 42_cloud1/srcs/.env.sample 42_cloud1/srcs/.env &&
          echo "WORDPRESS_HOST={{ public_ip_result.stdout }}" &&
          make -C 42_cloud1/srcs
        '
